name: json_ui_builder_example
description: Example application for json_ui_builder package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_ui_builder:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
